# Generated by Django 4.2.5 on 2023-09-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_alter_comment_user_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
