# Generated by Django 4.2.5 on 2023-09-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='This is a category description.'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='#', upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
    ]
