# Generated by Django 4.2.5 on 2023-10-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_description_category_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='This is a user description.'),
        ),
    ]
