# Generated by Django 4.2.5 on 2023-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='#', upload_to='user_images/'),
        ),
    ]
