# Generated by Django 4.2.5 on 2023-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_commentlike_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
